import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import { cn } from '@/lib/utils';
import { montserrat } from '@/components/ui/fonts';
import { Toaster } from '@/components/ui/Toaster';
import { TooltipProvider } from '@/components/ui/Tooltip';
import { SessionProvider } from '@/providers/SessionProvider';
import { getAuthSession } from '@/lib/get-session';

export const metadata: Metadata = {
  title: 'Movies Watchlist',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const session = await getAuthSession();

  return (
    <html
      lang="en"
      className={cn(
        'bg-white text-slate-900 antialiased light',
        montserrat.className
      )}
    >
      <body className="min-h-screen pt-12 antialiased bg-slate-50">
        <SessionProvider session={session}>
          <TooltipProvider>
            <Navbar />
            <div className="h-full px-4 pt-12 mx-auto sm:container max-w-7xl">
              {children}
            </div>
            <Toaster />
          </TooltipProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
