version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: movies-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  postgres:
    driver: local
  redis:
